### PR TITLE
Fix some typos in FlagShooter

### PR DESCRIPTION
**Pull request by PistonMiner**
Compiles, but haven't tried running it as I don't have a test setup.

### CODE REVIEW

**Comment by Trolldemorted** [comment]
`localJ` and `localI` are always equal, right? So we could just drop one of them?

**Comment by PistonMiner** [comment]
My understanding was that `i` was the index of the team the instance is for, and `j` the index of the instance for that specific team, with each team having multiple instances, but it's possible I'm misunderstanding the code.

**Comment by Trolldemorted** [comment]
cc @Savallator

**Comment by Trolldemorted** [comment]
Ah yeah you were right, they were equal but they shouldn't

**Comment by Savallator** [comment]
Did anyone actually test it before blindly hitting merge? Because while i have not yet looked into it, i suspect that was deliberately equal.

**Comment by Savallator** [comment]
Or, after looking in the code: LocalJ is not even used apart from debug output, so maybe instead of blindly changing names, restructure it so it is no longer needed.

**Comment by Savallator** [comment]
And for testing you just need a computer with working docker. You can then start the Database, Engine and Flagsink and test the Flagshooter.

**Pull request merged**
