### PR TITLE
added pr and nightly builds to the pipeline

### PR DESCRIPTION
**Pull request by M-Munier**

### CODE REVIEW

**Comment by M-Munier** [comment]
ok tbh I don't quite get the explicit pr statement in the yaml since the checks seem to run anyways

**Comment by Trolldemorted** [comment]
Why did you include it then?

**Comment by M-Munier** [comment]
because i dont undestand why our checks get triggered for pr at all

**Comment by M-Munier** [comment]
i did it an then realized that it somehow triggered

**Comment by Trolldemorted** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml

"If no pr triggers appear in your YAML file, pull request builds are automatically enabled for all branches"

**Pull request closed without merging**
