### PR TITLE
Scoreboard api

### PR DESCRIPTION
**Pull request by Savallator**
The Implementation of the API changes required for the new scoreboard.

### CODE REVIEW

**Comment by mauricesvp** [comment]
When the new scoreboard is ready we can merge this, before that I don't really want to do that.

**Comment by Savallator** [comment]
It is ready though...

**Comment by ldruschk** [comment]
I am still working a bit on the stability of the scoreboard, I can merge it later today when I am done and directly deploy it together with the new Scoreboard

**Comment by ldruschk** [comment]
Up and running on the test setup now, together with the new scoreboard :)

**Comment by mauricesvp** [comment]
Is it a problem on my end or why are the symbols not loading? (I did clear the cache)

**Comment by ldruschk** [comment]
> Is it a problem on my end or why are the symbols not loading? (I did clear the cache)

Could you raise an issue in the scoreboard repository? https://github.com/enowars/bambi-scoreboard/issues

@Trolldemorted mentioned this yesterday as well, apparently some resources cause a 404 reply but for some reason it works for me. Could you include the list of the resources which can't be fetched?

**Comment by mauricesvp** [comment]
Interestingly I had the same errors yesterday, but different ones now oO But both times resulting in no icons

**Pull request merged**
